<a href="https://colab.research.google.com/github/hafezi1403/special2/blob/main/Hafezi6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Beoadcasting

In [24]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [25]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [26]:
import numpy as np
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [27]:
import numpy as np
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [28]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
argmin(dist)

0

Book

In [29]:
import pandas as pd
# Create URL
url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/data.json'
# Load data
dataframe = pd . read_json ( url , orient= 'columns' )
# View the first two rows
dataframe . head ( 2 )

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0

In [30]:
import pandas as pd
# Create URL
url = 'https://machine-learning-python-cookbook.s3.amazonaws.com/data.parquet'
# Load data
dataframe = pd . read_parquet ( url )
# View the first two rows
dataframe . head ( 2 )

integer             datetime  category
0        5  2015-01-01 00:00:00         0
1        5  2015-01-01 00:00:01         0

In [31]:
! pip install pandavro

In [32]:
import requests
import pandavro as pdx
# Create URL
url = 'https://machine-learning-python-cookbook.s3.amazonaws.com/data.avro'
# Download file
r = requests . get ( url )
open ( 'data.avro' , 'wb' ) . write ( r . content )
# Load data
dataframe = pdx . read_avro ( 'data.avro' )
# View the first two rows
dataframe . head ( 2 )

integer             datetime  category
0        5  2015-01-01 00:00:00         0
1        5  2015-01-01 00:00:01         0

In [33]:
! pip install sqlalchemy

In [34]:
import pandas as pd
from sqlalchemy import create_engine
# Create a connection to the database
database_connection = create_engine ( 'sqlite:///sample.db' )
# Load data
dataframe = pd . read_sql_query ( 'SELECT * FROM data' , database_connection )
# View first two rows
dataframe . head ( 2 )

OperationalError: (sqlite3.OperationalError) no such table: data
[SQL: SELECT * FROM data]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [35]:
! pip install pymysql

In [37]:
import pymysql
import pandas as pd
# Create a DB connection
# Use the following example to start a DB instance
# https://github.com/kylegallatin/mysql-db-example
conn = pymysql . connect (
                  host= 'localhost' ,
                  user= 'root' ,
                  password = "" ,
                  db= 'db' ,
                         )
# Read the SQL query into a dataframe
dataframe = pd . read_sql ( "select * from data" , conn )
# View the first two rows
dataframe . head ( 2 )

OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)")

In [38]:
import pandas as pd
# Google Sheet URL that downloads the sheet as a CSV
url = "https://docs.google.com/spreadsheets/d/" \
"1ehC-9otcAuitqnmWksqt1mOrTRCL38dv0K9UjhwzTOA/export?format=csv"
# Read the CSV into a dataframe
dataframe = pd . read_csv ( url )
# View the first two rows
dataframe . head ( 2 )

integer            datetime  category
0        5  2015-01-01 0:00:00         0
1        5  2015-01-01 0:00:01         0

In [39]:
! pip install requests

In [40]:
import requests
# URL to download the txt file from
txt_url = "https://machine-learning-python-cookbook.s3.amazonaws.com/text.txt"
# Get the txt file
r = requests . get ( txt_url )
# Write it to text.txt locally
with open ( 'text.txt' , 'wb' ) as f:
  f.write ( r . content )
# Read in the file
with open ( 'text.txt' , 'r' ) as f:
  text = f.read ()
# Print the content
print ( text )

Hello there!


In [41]:

import pandas as pd
# Create URL
url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'
# Load data as a dataframe
dataframe = pd . read_csv ( url )
# Show first five rows
dataframe . head ( 5 )

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [42]:
import pandas as pd
# Create a dictionary
dictionary = {
"Name" : [ 'Jacky Jackson' , 'Steven Stevenson' ],
"Age" : [ 38 , 25 ],
"Driver" : [ True , False ]
}
dataframe = pd . DataFrame ( dictionary )
# Show DataFrame
dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [43]:
dataframe [ "Eyes" ] = [ "Brown" , "Blue" ]
# Show DataFrame
dataframe

Name  Age  Driver   Eyes
0     Jacky Jackson   38    True  Brown
1  Steven Stevenson   25   False   Blue

In [44]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'
# Load data
dataframe = pd . read_csv ( url )
# Show two rows
dataframe . head ( 2 )

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [45]:
dataframe . shape
# Show statistics
dataframe . describe ()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [46]:
# Show info
dataframe . info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      1313 non-null   object 
 1   PClass    1313 non-null   object 
 2   Age       756 non-null    float64
 3   Sex       1313 non-null   object 
 4   Survived  1313 non-null   int64  
 5   SexCode   1313 non-null   int64  
dtypes: float64(1), int64(2), object(3)
memory usage: 61.7+ KB
